name: ON-PUSH

permissions: write-all

on:
  push:
    branches:
      - "**"  # Trigger for any branch on push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Poetry
        run: pipx install poetry

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'poetry'

      - name: Install dependencies
        run: make install

      - name: QA
        run: make qa

      - name: Test
        run: make test
